# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ace7f6399bf06ac31304db4629485d4aaf815a58ec089add5c473691c53f026bf128a60ea093f2c578743f69b20ac82236091e2120d57adc46aea3594c19dd7d

test:
  secret_key_base: d0b8112c668db5d25639764d8321181aa59bd071bbbb63d8b4e34a7fc22e531d7f2d0b6aff9f411aaee3c0054c4de6f319dd9af00a150f372c4e383d27c0546f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
