# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Project.create(id: 1, title: "Городской портал")
Project.create(id: 2, title: "АСУ ТП ДГ")
Project.create(id: 3, title: "Управление производством")
Project.create(id: 4, title: "IT-Пром")
Project.create(id: 5, title: "Интернет-магазин: керамика")
Project.create(id: 6, title: "Визитка для завода")
Project.create(id: 7, title: "ИС ТНТ МИВ")
Project.create(id: 8, title: "ODesk")
Project.create(id: 9, title: "Free-lance")
Project.create(id: 10, title: "Инфраструктура")

Component.create(id: 1, title: "Web-приложение", project_id: 1)
Component.create(id: 2, title: "Мобильное приложение", project_id: 1)
Component.create(id: 3, title: "Документация", project_id: 1)
Component.create(id: 4, title: "Web-приложение", project_id: 2)
Component.create(id: 5, title: "Мобильное приложение", project_id: 2)
Component.create(id: 6, title: "Мобильное приложение", project_id: 3)
Component.create(id: 7, title: "Web-приложение", project_id: 3)
Component.create(id: 8, title: "Web-приложение", project_id: 4)
Component.create(id: 9, title: "Мобильное приложение", project_id: 4)
Component.create(id: 10, title: "Web-приложение", project_id: 5)
Component.create(id: 11, title: "Мобильное приложение", project_id: 5)
Component.create(id: 12, title: "Документация", project_id: 5)
Component.create(id: 13, title: "Web-приложение", project_id: 6)
Component.create(id: 14, title: "Мобильное приложение", project_id: 6)
Component.create(id: 15, title: "Документация", project_id: 6)
Component.create(id: 16, title: "Desktop-приложение", project_id: 6)
Component.create(id: 17, title: "Сервис", project_id: 6)
Component.create(id: 18, title: "Web-приложение", project_id: 7)
Component.create(id: 19, title: "Мобильное приложение", project_id: 7)
Component.create(id: 20, title: "Документация", project_id: 7)
Component.create(id: 21, title: "Web-приложение", project_id: 8)
Component.create(id: 22, title: "Мобильное приложение", project_id: 8)
Component.create(id: 23, title: "Документация", project_id: 8)
Component.create(id: 24, title: "Desktop-приложение", project_id: 8)
Component.create(id: 25, title: "Web-приложение", project_id: 9)
Component.create(id: 26, title: "Мобильное приложение", project_id: 9)
Component.create(id: 27, title: "Документация", project_id: 9)
Component.create(id: 28, title: "Web-приложение", project_id: 10)
Component.create(id: 29, title: "Мобильное приложение", project_id: 10)
Component.create(id: 30, title: "Документация", project_id: 10)

CurrentState.create(id: 1, project: 1, component: "Web-приложение")